### PR TITLE
Postgres: Fix Select statement ordering

### LINKED ISSUE #6425: Postgres `SELECT ... LIMIT 1 FOR UPDATE` unparsable
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The Postgres docs (https://www.postgresql.org/docs/current/sql-select.html) seem to suggest that the row-level locking syntax `FOR UPDATE` follows after `LIMIT` clauses. However, SQLFluff fails to lint the query `SELECT foo FROM bar LIMIT 1 FOR UPDATE`. This query syntax is acceptable to Postgres, as is the opposite order `SELECT foo FROM bar FOR UPDATE LIMIT 1`. SQLFluff only accepts this latter structure, though.

### Expected Behaviour

Linting successful with no parsing errors.

### Observed Behaviour

```
== [stdin] FAIL                                                                                                                                                
L:   1 | P:  29 |  PRS | Line 1, Position 29: Found unparsable section: 'FOR
                       | UPDATE'
WARNING: Parsing errors found and dialect is set to 'postgres'. Have you configured your dialect correctly?
All Finished 📜 🎉!
```

### How to reproduce

```bash
echo 'SELECT foo FROM bar LIMIT 1 FOR UPDATE' | sqlfluff lint --dialect=postgres -
```

### Dialect

postgres

### Version

sqlfluff, version 3.2.5
Python 3.11.10

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by WittierDinosaur**
### Brief summary of the change made
Fixes #6425 

Also adds the fetch clause.

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/postgres/select.sql [hunk 1]
```diff
@@ -78,8 +78,9 @@ SELECT col1, col2
 FROM mytable1
 JOIN mytable2 ON col1 = col2
 ORDER BY sync_time ASC
+LIMIT 1
 FOR SHARE OF mytable1, mytable2 SKIP LOCKED
-LIMIT 1;
+;
```
Comment (greg-finley) [inline test/fixtures/dialects/postgres/select.sql:83]: maybe even test it both ways?

**Review by greg-finley — APPROVED** [review]
