### PR TITLE
Fix tsql dialect `EXEC = @Variable StoredProc` Failed Parsing Bug (#3070)

### LINKED ISSUE #3070: tsql - EXEC @Variable = StoredProcedure (used to capture stored procedure RETURN value)- Unparsable Error
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I attempted to lint the following T-SQL:

```t-sql
DECLARE @FailedChecks INT;

EXEC @FailedChecks = auditing.PreProcessingChecks;

```

If the EXEC line is changed to be just `EXEC auditing.PreProcessingChecks;` the file can be successfully parsed.

### Expected Behaviour

I expected a successful lint with the following output:

```
All Finished 📜 🎉!
```

### Observed Behaviour

I received the following error output:

```
== [WePredict-Database-Deepview-Gamma\DataProc.PerformProcessing.sql] FAIL
L:   3 | P:  20 |  PRS | Line 3, Position 20: Found unparsable section: '=
                       | auditing.PreProcessingChecks;\n'
All Finished 📜 🎉!
```

### How to reproduce

Create a `test.sql` file containing the content:

```t-sql
DECLARE @FailedChecks INT;

EXEC @FailedChecks = auditing.PreProcessingChecks;


```

Run the command `sqlfluff lint test.sql --dialect tsql`

### Dialect

tsql

### Version

sqlfluff, version 0.12.0

### Configuration

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 120
indent_unit = space
unquoted_identifiers_policy = column_aliases

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by MartynJones87**
### Brief summary of the change made

Fixes #3070 

Add support, for the tsql dialect, for an optional `= @Variable` between an `EXEC` and the following stored procedure name, to support capturing the RETURN value from the stored procedure (as documented [here](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/return-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#b-returning-status-codes))

### Are there any other side effects of this change that we should be aware of?

N/A

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/tsql/execute.sql [hunk 1]
```diff
@@ -22,3 +22,10 @@ EXECUTE sp_addextendedproperty
 @level0name = N'my_schema_name',
 @level1type = N'my_object_type',
 @level1name = N'my_object_name'
+
+
+-- Executing a stored procedure and capturing the RETURN value in a variable
+EXEC @pRes = dbo.ProcTestDefaults;
+EXEC @pRes = dbo.ProcTestDefaults @p1 = DEFAULT;
+EXECUTE @pRes = dbo.ProcTestDefaults;
+EXECUTE @pRes = dbo.ProcTestDefaults @p1 = DEFAULT;
```
Comment (tunetheweb) [inline test/fixtures/dialects/tsql/execute.sql:31]: Make sure files end in newlines:

```suggestion
EXECUTE @pRes = dbo.ProcTestDefaults @p1 = DEFAULT;

```

 Btw we have a [editorconfig](https://editorconfig.org/) file if your IDE supports that (some like VS Code require installing an extension), and also support [pre-commit](https://github.com/sqlfluff/sqlfluff/blob/main/CONTRIBUTING.md#pre-commit-config), both of which will auto correct this.

**Review by tunetheweb — APPROVED** [review]
LGTM, with one nit.
