### PR TITLE
L003: Ignore indentation of lines that only exist in templated space

### LINKED ISSUE #2270: For templated regions, L003 complains that indentation is wrong, even though the raw (pre-template expansion) code looks correctly indented
## Expected Behaviour

The indentation after a templated area would behave in a way that is visually similar to other lines.

## Observed Behaviour

When a column in a query is templated and then aliased with a single space after the templated area an L003 error is raised unless there is a full indentation after the templated area.

## Steps to Reproduce

Using the dbt templator and the included macro lint the following sql:

```sql
{% macro get_keyed_nulls(columns) %}

  COALESCE({{columns}}, MD5(-1)) 

{% endmacro %}

SELECT
    table_id,
    {{ get_keyed_nulls('other_id') }} AS other_id
FROM my_table
```

## Dialect

Snowflake

## Version
Include the output of `sqlfluff --version` along with your Python version.
If you are using dbt then please additionally include the dbt version.

```console
==== sqlfluff ====
sqlfluff:                0.9.0 python:                  3.8.6
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:                 dbt
dbt:                   =0.19.1
```

## Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt

[sqlfluff:templater:dbt]
project_dir = ./
```

### PR DESCRIPTION
**Pull request by barrywhart**
### Brief summary of the change made
Fixes #2270 

This is a follow-on fix to #2304. The prior PR fixed a slightly different bug than the one described in the issue. This one fixes the reported issue.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/issue_1608.sql.after [hunk 1]
```diff
@@ -8,7 +8,7 @@ final as
 (
     select
         col_name,
-        {{- echo('col_name') -}}        as col_name2
+        {{- echo('col_name') -}} as col_name2
```
Comment (barrywhart) [inline plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/issue_1608.sql.after:11]: The new test results are clearly better -- the old way, we were checking that L003 added "indentation" in the middle of a line. 🤯🤣

**Comment by barrywhart** [comment]
I think all the tests are passing now. We shall see... 🍿

**Review by tunetheweb — APPROVED** [review]
Change LGTM if test pass (including coverage - my bug bear 😁 though no choice in that!).
