### PR TITLE
TSQL: Support nested joins

### LINKED ISSUE #2676: TSQL: Support for nested JOINs / delayed ON statements
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

TSQL allows for nested JOINs (or delayed ON statements depending on your perspective).  SQLFluff currently does not support this.

For example:
```
SELECT
    1 AS RegionCode
FROM BA 
LEFT OUTER JOIN I 
	LEFT OUTER JOIN P 
		ON I.Pcd = P.Iid 
	ON BA.Iid = I.Bcd 
```

### Expected Behaviour

The above code parses.

### Observed Behaviour

Parsing fails.

### How to reproduce

Parse the above code using the TSQL dialect.

### Dialect

TSQL

### Version

latest main

### Configuration

```
[sqlfluff]
dialect = tsql
rules = L001,L002,L005,L006,L008,L009,L052

[sqlfluff:rules]
max_line_length = 140
comma_style = leading
single_table_references = qualified
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = both

[sqlfluff:rules:L052]
require_final_semicolon = True
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tunetheweb**
### Brief summary of the change made

Fixes #2676 

### Are there any other side effects of this change that we should be aware of?
This change means a `JOIN` clause can now have multiple tables, so multiple aliases. So we had to change `get_eventual_alias` to `get_eventual_aliases`.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/tsql/inner_joins.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+SELECT
+    1 AS RegionCode
+FROM BA 
+LEFT OUTER JOIN I
```
Comment (barrywhart) [inline test/fixtures/dialects/tsql/inner_joins.sql:4]: I would consider these joins to be chained one after another, not nested. It's kinda similar to arithmetic, e.g. `1 + 2 + 3 + 4`. If I parse `SELECT 1 + 2 + 3 + 4`, it looks like:
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        select_statement:
[L:  1, P:  1]      |            select_clause:
[L:  1, P:  1]      |                keyword:                                      'SELECT'
[L:  1, P:  7]      |                [META] indent:
[L:  1, P:  7]      |                whitespace:                                   ' '
[L:  1, P:  8]      |                select_clause_element:
[L:  1, P:  8]      |                    expression:
[L:  1, P:  8]      |                        literal:                              '1'
[L:  1, P:  9]      |                        whitespace:                           ' '
[L:  1, P: 10]      |                        binary_operator:                      '+'
[L:  1, P: 11]      |                        whitespace:                           ' '
[L:  1, P: 12]      |                        literal:                              '2'
[L:  1, P: 13]      |                        whitespace:                           ' '
[L:  1, P: 14]      |                        binary_operator:                      '+'
[L:  1, P: 15]      |                        whitespace:                           ' '
[L:  1, P: 16]      |                        literal:                              '3'
[L:  1, P: 17]      |                        whitespace:                           ' '
[L:  1, P: 18]      |                        binary_operator:                      '+'
[L:  1, P: 19]      |                        whitespace:                           ' '
[L:  1, P: 20]      |                        literal:                              '4'
[L:  1, P: 21]      |            [META] dedent:
[L:  1, P: 21]      |    newline:                                                  '\n'
```

Could we organize it to parse that way instead? That seems more correct.

Comment (barrywhart) [reply test/fixtures/dialects/tsql/inner_joins.sql:4]: Oh, never mind. It _is_ nested, because of the sequence of the `ON` clauses. Tricky!!

**Review by barrywhart — APPROVED** [review]

File: test/fixtures/dialects/tsql/inner_joins.sql (hunk 1 above)
Comment (tunetheweb) [reply test/fixtures/dialects/tsql/inner_joins.sql:4]: Yup exactly. I was confused at first why it didn’t just work until I saw that.
