### PR TITLE
Fill in Gap for Snowflake `CREATE` Syntax Parsing

### LINKED ISSUE #6513: Gap in Snowflake `CREATE` Syntax Parsing
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

SQLFluff throws a parsing error when it encounters a valid Snowflake SQL statement.

### Expected Behaviour

This should correctly parse.

### Observed Behaviour

The following error is printed 
```
== [test.sql] FAIL 
L:   2 | P:   3 |  PRS | Line 2, Position 3: Found unparsable section:
                       | 'STORAGE_INTEGRATION=$your_variable\n  URL...'
```

### How to reproduce

CREATE STAGE foo.bar
  STORAGE_INTEGRATION=$your_variable
  URL=$your_variable;

### Dialect

Snowflake

### Version

v3.3.0

### Configuration

`N/A`

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by LoganPrice344**
Fixes #6513

### CODE REVIEW

File: test/fixtures/dialects/snowflake/create_stage.sql [hunk 1]
```diff
@@ -105,3 +105,7 @@ CREATE OR REPLACE STAGE foo.bar
 
 CREATE OR ALTER STAGE foo.bar
   URL = 's3://foobar';
+
+CREATE STAGE foo.bar
```
Comment (WittierDinosaur) [inline test/fixtures/dialects/snowflake/create_stage.sql:109]: There's quite a lot of additions in this PR - can we add some more tests?

**Review by WittierDinosaur — APPROVED** [review]

File: test/fixtures/dialects/snowflake/create_stage.sql (hunk 1 above)
Comment (LoganPrice344) [reply test/fixtures/dialects/snowflake/create_stage.sql:109]: Are the new testing additions sufficient?
