### PR TITLE
DuckDB: Add support for SET

### LINKED ISSUE #7325: [duckdb] Found unparsable section "SET VARIABLE"
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff can not parse "SET VARIABLE" in duckdb.

### Expected Behaviour

sqlfluff should parse successfully.

### Observed Behaviour

L:   1 | P:   1 |  PRS | Line 1, Position 1: Found unparsable section: 'SET                                                                                        
                       | VARIABLE my_var = 30;\nSELECT 20 + ge...'

### How to reproduce

Run sqlfluff lint

```sql
SET VARIABLE my_var = 30;
SELECT 20 + getvariable('my_var') AS total;
```

### Dialect

duckdb

### Version

3.5.0

### Configuration

[sqlfluff]
dialect = duckdb

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by aammett**
### Brief summary of the change made

Adds comprehensive SET statement support for DuckDB dialect, including `SET VARIABLE`, `SET GLOBAL`, `SET SESSION`, and basic `SET parameter = value` patterns with both `=` and `TO` assignment operators.

Previously, DuckDB SET statements were unparsable and caused errors like: `Found unparsable section: 'SET VARIABLE my_var = 30;'`

Fixes #7325

### Are there any other side effects of this change that we should be aware of?

None. The implementation only extends existing functionality without breaking changes:

- Only adds new DuckDB-specific patterns 
- Does not affect other dialects or existing functionality
- All existing DuckDB features continue to work unchanged

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - [ ] `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - [x] `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - [ ] Full autofix test cases in `test/fixtures/linter/autofix`.
  - [ ] Other.
- [x] Added appropriate documentation for the change.
- [ ] Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/duckdb/set.sql [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+-- Basic SET parameter = value
+SET memory_limit = '10GB';
+SET threads = 1;
+
+-- SET parameter TO value
+SET threads TO 1;
+
+-- SET SESSION parameter = value
+SET SESSION default_collation = 'nocase';
```
[the remark this answers is not in the document]
Comment (aammett) [reply test/fixtures/dialects/duckdb/set.sql:13]: LOCAL: Not yet implemented

**Comment by aammett** [comment]
Hello @peterbud,
can I please get a review for this PR ?

File: src/sqlfluff/dialects/dialect_duckdb.py [hunk 2]
```diff
@@ -1130,6 +1130,45 @@ class CopyStatementSegment(postgres.CopyStatementSegment):
...
+
+    type = "set_statement"
+
+    match_grammar = Sequence(
+        "SET",
+        OneOf(
+            Sequence(
+                "VARIABLE",
+                Ref("NakedIdentifierSegment"),  # variable_name
+                Ref("EqualsSegment"),
```
Comment (peterbud) [inline src/sqlfluff/dialects/dialect_duckdb.py]: The spec also allows "TO", not just `=`

File: src/sqlfluff/dialects/dialect_duckdb.py [hunk 3]
```diff
@@ -1130,6 +1130,45 @@ class CopyStatementSegment(postgres.CopyStatementSegment):
...
+                OneOf(
+                    Ref("LiteralGrammar"),
+                    Ref("NakedIdentifierSegment"),
+                    Ref("QuotedIdentifierSegment"),
+                ),
+            ),
+            Sequence(
+                OneOf("SESSION", "GLOBAL", optional=True),
```
Comment (peterbud) [inline src/sqlfluff/dialects/dialect_duckdb.py]: While we are here, the spec also allows "LOCAL", so it would be good to add.

**Review by peterbud — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks good, I had two nitpicks only

**Review by peterbud — APPROVED** [review]
