### PR TITLE
Databricks: parse MERGE clauses with NOT MATCHED BY TARGET/SOURCE (fixes #7608)

### LINKED ISSUE #7608: Databricks: Parser issue with `MERGE INTO`
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

from #7082, the second issue fails to parse

### Expected Behaviour

This should parse

### Observed Behaviour

```sh
==== parsing violations ====
L:  25 | P:   1 |  PRS | Line 25, Position 1: Found unparsable section: 'when not matched
                       | by target\nthen\ninsert (...'
```

### How to reproduce

```sql
merge into mydb_stg.dummy_table as dest
using
_tempDeDupRaw as src
on
dest.col_a = src.col_a
and dest.col_b = src.col_b
and dest.col_c = src.col_c
and dest.col_d <=> src.col_d
and dest.col_e <=> src.col_e
and dest.col_f <=> src.col_f
and dest.col_g <=> src.col_g
when matched
and dest.ts_extracted < src.ts_extracted
and not (dest.id = src.id)
then
update
set
dest.file_path = src.file_path
, dest.ts_updated = current_timestamp()
, dest.ts_inserted_raw = src.ts_inserted_raw
, dest.ts_loaded_raw = src.ts_loaded_raw
, dest.ts_loaded_drp = src.ts_loaded_drp
, dest.ts_extracted = src.ts_extracted
, dest.id = src.id
when not matched by target
then
insert (
file_path
, ts_inserted_stg
, ts_updated
, ts_inserted_raw
, ts_loaded_raw
, ts_loaded_drp
, ts_extracted
, col_a
, col_b
, col_c
, col_d
, col_e
, col_f
, col_g
, id
) values (
src.file_path
, current_timestamp()
, current_timestamp()
, src.ts_inserted_raw
, src.ts_loaded_raw
, src.ts_loaded_drp
, src.ts_extracted
, src.col_a
, src.col_b
, src.col_c
, src.col_d
, src.col_e
, src.col_f
, src.col_g
, src.id
)
when not matched by source
then
delete
```

### Dialect

databricks

### Version

4.0.4

### Configuration

```ini
[sqlfluff]
dialect = databricks
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by api2062**
### Brief summary of the change made
Fixes #7608.

This updates the Databricks parser grammar for `MERGE` to support:
- `WHEN NOT MATCHED BY TARGET THEN INSERT ...`
- `WHEN NOT MATCHED BY SOURCE THEN DELETE/UPDATE ...`

It also fixes a parsing edge case where `INSERT ... VALUES (...)` in a merge clause could consume a following `WHEN` as an alias, preventing subsequent merge clauses from parsing.

Changes included:
- Added `SOURCE` and `TARGET` to Databricks unreserved keywords.
- Added Databricks-specific merge clause handling:
  - `MergeNotMatchedClauseSegment` with optional `BY TARGET`
  - `MergeNotMatchedBySourceClauseSegment`
  - Updated `MergeMatchSegment` to include `BY SOURCE` clauses
- Overrode Databricks `MergeInsertClauseSegment` to explicitly parse values in merge inserts.
- Added regression parser fixture:
  - `test/fixtures/dialects/databricks/merge_into.sql`
  - Generated `test/fixtures/dialects/databricks/merge_into.yml`

### Are there any other side effects of this change that we should be aware of?
- Databricks dialect now recognizes `SOURCE` and `TARGET` as unreserved keywords.
- This change is scoped to Databricks merge parsing behavior.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - [x] `.sql`/`.yml` parser test cases in `test/fixtures/dialects`.
  - [ ] `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - [ ] Full autofix test cases in `test/fixtures/linter/autofix`.
  - [ ] Other.
- [ ] Added appropriate documentation for the change.
- [ ] Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/databricks/merge_into.sql [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+, src.col_c
+, src.col_d
+, src.col_e
+, src.col_f
+, src.col_g
+, src.id
+)
+when not matched by source
+then
+delete
```
[the remark this answers is not in the document]
Comment (api2062) [reply test/fixtures/dialects/databricks/merge_into.sql:62]: Thanks for the suggestion. I expanded test/fixtures/dialects/databricks/merge_into.sql to cover the extra Databricks MERGE branches you called out

File: src/sqlfluff/dialects/dialect_databricks.py [hunk 2]
```diff
@@ -51,6 +51,7 @@
 databricks_dialect.sets("unreserved_keywords").difference_update(RESERVED_KEYWORDS)
 databricks_dialect.sets("reserved_keywords").clear()
 databricks_dialect.sets("reserved_keywords").update(RESERVED_KEYWORDS)
+databricks_dialect.sets("unreserved_keywords").update(["SOURCE", "TARGET"])
```
Comment (WittierDinosaur) [inline src/sqlfluff/dialects/dialect_databricks.py]: This isn't the right place to add these keywords, please can you add them to https://github.com/sqlfluff/sqlfluff/blob/0a1cd96bac9999495172ec7e86d99998a06eba1f/src/sqlfluff/dialects/dialect_databricks_keywords.py#L25

Comment (api2062) [reply src/sqlfluff/dialects/dialect_databricks.py]: Fixed. Thanks.

**Review by WittierDinosaur — APPROVED** [review]
LGTM
