### PR TITLE
Snowflake: alter table on delete and update support

### LINKED ISSUE #6472: Snowflake ForeignKey constraint ON DELETE not recognised
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.


### What Happened

Whilst attempting to `lint` some Snowflake SQL that contained an `ALTER TABLE` to add a Foreign Key constraint with `ON DELETE`

```sql
CREATE TABLE TABLE1(
    TABLE1_KEY          VARCHAR(255)    NOT NULL,
    TABLE1              VARCHAR(16)     NOT NULL,
    TABLE1_TYPE         VARCHAR(255)    NOT NULL,
    TABLE1_FORMAT_ID    VARCHAR(255),
    CONSTRAINT PK158 PRIMARY KEY (TABLE1_KEY)
)
;

CREATE TABLE REF_TABLE2_FORMAT(
    TABLE2_FORMAT_ID    VARCHAR(255)    NOT NULL,
    TABLE2_FORMAT       VARCHAR(16)     NOT NULL,
    CONSTRAINT PK52_1 PRIMARY KEY (TABLE2_FORMAT_ID)
)
;

ALTER TABLE TABLE1 ADD CONSTRAINT REFREF_TABLE1_FORMAT218
    FOREIGN KEY (TABLE1_FORMAT_ID)
    REFERENCES REF_TABLE2_FORMAT(TABLE2_FORMAT_ID)
    ON DELETE NO ACTION
;
```

`sqlfluff` fails with the following error

```
== [dummy.sql] FAIL                                                                                                                                                                                                                                                                                                
L:  21 | P:   5 |  PRS | Line 21, Position 5: Found unparsable section: 'ON
                       | DELETE NO ACTION\n;'
WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?
All Finished 📜 🎉!

```

Looking at the dialect code the `InlineConstraintGrammar` does not handle all supported options for Foreign Keys, only Primary/Unique Keys described in

https://docs.snowflake.com/en/sql-reference/sql/create-table-constraint#syntax-for-inline-constraints

### Expected Behaviour

The SQL should lint successfully with zero return code

### Observed Behaviour

An error message is produced and the command exits with a non-zero return code

```
== [dummy.sql] FAIL                                                                                                                                                                                                                                                                                                
L:  21 | P:   5 |  PRS | Line 21, Position 5: Found unparsable section: 'ON
                       | DELETE NO ACTION\n;'
WARNING: Parsing errors found and dialect is set to 'snowflake'. Have you configured your dialect correctly?
All Finished 📜 🎉!

```

Removing `ON DELETE RESTRICT` from the constraint allows the SQL to lint successfully

### How to reproduce

Create `dummy.sql` from the following

```
CREATE TABLE TABLE1(
    TABLE1_KEY          VARCHAR(255)    NOT NULL,
    TABLE1              VARCHAR(16)     NOT NULL,
    TABLE1_TYPE         VARCHAR(255)    NOT NULL,
    TABLE1_FORMAT_ID    VARCHAR(255),
    CONSTRAINT PK158 PRIMARY KEY (TABLE1_KEY)
)
;

CREATE TABLE REF_TABLE2_FORMAT(
    TABLE2_FORMAT_ID    VARCHAR(255)    NOT NULL,
    TABLE2_FORMAT       VARCHAR(16)     NOT NULL,
    CONSTRAINT PK52_1 PRIMARY KEY (TABLE2_FORMAT_ID)
)
;

ALTER TABLE TABLE1 ADD CONSTRAINT REFREF_TABLE1_FORMAT218
    FOREIGN KEY (TABLE1_FORMAT_ID)
    REFERENCES REF_TABLE2_FORMAT(TABLE2_FORMAT_ID)
    ON DELETE NO ACTION
;
```

execute the following command

```cmd
sqlfluff lint --dialect snowflake dummy.sql

```

### Dialect

Snowflake

### Version

sqlfluff, version 3.2.4

Python 3.11.6

### Configuration

`.sqlfluff` contains

```
[sqlfluff]
exclude_rules = LT01, LT02, LT05, LT12, LT13, CV06, CP01, RF04

large_file_skip_byte_limit = 0
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by WobblyRobbly**
### Brief summary of the change made
This change allows for Snowflake ALTER TABLE to define a FOREIGN KEY that has uses the ON DELETE / ON UPDATE 

Fixes #6472 

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [ *] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/snowflake/alter_table.sql [hunk 1]
```diff
@@ -51,3 +51,7 @@ ALTER TABLE "my_table" ALTER COLUMN "my_column" SET MASKING POLICY my_masking_po
 ALTER TABLE SAMPLE_DB.SAMPLE_SCHEMA.TBL UNSET COMMENT;
 
 ALTER TABLE table1 UNSET COMMENT, DATA_RETENTION_TIME_IN_DAYS;
+
+ALTER TABLE table1 ADD CONSTRAINT constraint1 FOREIGN KEY (address) REFERENCES addresses (address) ON DELETE RESTRICT ON UPDATE CASCADE;
+
+ALTER TABLE table2 ADD CONSTRAINT constraint2 FOREIGN KEY (address) REFERENCES addresses (address) ON DELETE NO ACTION ON UPDATE SET NULL;
```
Comment (WittierDinosaur) [inline test/fixtures/dialects/snowflake/alter_table.sql:57]: Can you add at least one `MATCH` example to the unit tests?

Comment (WobblyRobbly) [reply test/fixtures/dialects/snowflake/alter_table.sql:57]: Thanks for the review @WittierDinosaur . I've update the PR with additional test case

**Review by alanmcruickshank — APPROVED** [review]
LGTM
