### PR TITLE
Oracle: Redesign slash as buffer executor

### LINKED ISSUE #7497: Oracle dialect fails to detect / (slash) as a statement terminator
### Search before asking

- [x] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The Oracle dialect fails to correctly identify and parse the / (slash) symbol when used as a statement terminator. In Oracle SQL and PL/SQL, the slash is the standard execution character used to terminate and execute blocks of code (such as CREATE PROCEDURE, CREATE TRIGGER, or anonymous blocks) within a script. Currently, SQLFluff does not recognize this as a valid delimiter, leading to parsing errors in multi-statement scripts.

### Expected Behaviour

SQLFluff should recognize the / character as a valid statement terminator, particularly for PL/SQL blocks, allowing multiple blocks to be defined and terminated sequentially within a single file.

### Observed Behaviour

The parser fails to recognize the `/` as a delimiter. Internal logic within `DelimiterGrammar` appears to be incorrectly defined as a `Sequence` that requires both a semicolon and a slash, or it simply fails to include the slash as a standalone alternative to the semicolon.

### How to reproduce

1. Create repro.sql:

```sql
-- This fails to parse the slash delimiter between blocks
CREATE PROCEDURE my_proc IS 
BEGIN 
    NULL; 
END;
/

BEGIN 
    NULL; 
END;
/
```

Run linting:

```bash
sqlfluff lint repro.sql --dialect oracle
```

### Dialect

oracle

### Version

4.0.4

### Configuration

Standard default configuration using `--dialect oracle`.

### Are you willing to work on and submit a PR to address the issue?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by saulotoledo**
### Brief summary of the change made
Fix issue in the `DelimiterGrammar` that was preventing `;` and `/` from acting as independent, valid alternatives for statement termination.

Fixes #7497.

### Are there any other side effects of this change that we should be aware of?
No.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/oracle/declare_function_blocks.sql [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+  IS
+    s sum_multiples;
+  BEGIN
+    RETURN s;
+  END get_sum;
+
+BEGIN
+  DBMS_OUTPUT.PUT_LINE('Test');
+END;
+/
```
Comment (saulotoledo) [inline test/fixtures/dialects/oracle/declare_function_blocks.sql]: I am considering dropping this file. The `multiple_blocks.sql` should be enough.

File: src/sqlfluff/rules/oracle/OR01.py
Comment (saulotoledo) [inline src/sqlfluff/rules/oracle/OR01.py:1]: Any suggestions to improve this?
I will review this rule again, but it seems wrong to have it dialect-specific. I think it is useful though. I accept suggestions on how to better handle it.

File: src/sqlfluff/rules/oracle/OR01.py [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    **Best practice**
+
+    .. code-block:: sql
+
+        SELECT 1 FROM dual;
+        /
+    """
+
+    name = "oracle.slash_terminator"
+    aliases = ("L069",)  # Using a new code
```
Comment (saulotoledo) [inline src/sqlfluff/rules/oracle/OR01.py]: I still have to read the guidelines for naming the rules. Should I add aliases? Any suggestions here?

File: src/sqlfluff/rules/structure/ST12.py [hunk 3]
```diff
@@ -129,6 +129,14 @@ def _whitespace_only_between(a, b) -> bool:
...
             j = i
             while j + 1 < n and _whitespace_only_between(terms[j], terms[j + 1]):
+                # Oracle allows a semicolon followed by a slash as a valid dual terminator.
+                # In this case we should not collapse them.
+                if (
+                    context.dialect.name == "oracle"
+                    and terms[j].raw == ";"
+                    and terms[j + 1].raw.strip() == "/"
+                ):
+                    break
```
Comment (saulotoledo) [inline src/sqlfluff/rules/structure/ST12.py]: Not fully tested yet. I did not like the idea of adding oracle-specific code here, but I see no other way of doing it for this case.

File: src/sqlfluff/dialects/dialect_oracle.py [hunk 4]
```diff
@@ -952,8 +965,15 @@
             ),
         ),
     ),
-    DelimiterGrammar=Sequence(
-        Ref("SemicolonSegment"), Ref("SlashStatementTerminatorSegment", optional=True)
+    DelimiterGrammar=OneOf(
+        Ref("SemicolonSegment"),
+        Ref("SlashStatementTerminatorSegment"),
+        # Rogue case: slash immediately after semicolon (no newline)
+        # We catch this so that the linter (OR01) can identify it and insert a newline.
```
Comment (saulotoledo) [inline src/sqlfluff/dialects/dialect_oracle.py]: I will review this again when changing the rule (see comments later).

**Comment by saulotoledo** [comment]
@WittierDinosaur, @keraion, you reviewed some of my previous PRs here. I would like to ask you for some guidance on my comments above. Could you help me with that? I would like to proceed in the right direction here. Then I will proceed with the fixes.

**Comment by keraion** [comment]
I'm trying to understand your intention here. In the linked issue, the sql you provide does parse the `;` and `/` as `statement_terminator`s and none of the tests here have them independent of one another. I think once I understand the parsing issue I can better assist with the rule changes.

**Comment by saulotoledo** [comment]
@keraion, I mixed 3 distinct things here, and it might be a good idea to split them into separate issues, but let me know what you think of them first:

1. Autofix collapsing `;\n/`:

```sql
BEGIN
    NULL;
END;
/ <---- This is removed 
```

```bash
== [repro_semicolon_slash.sql] FAIL                                                                                             
L:   3 | P:   4 | ST12 | Consecutive semicolons detected (count 2).
                       | [structure.consecutive_semicolons]
== [repro_semicolon_slash.sql] FIXED
```

This makes it impossible to use sqlfluff in a pipeline for autoformatting because it removes all `/` characters.

_Solution:_ fix the ST12 rule.

--
2. Not identifying an issue with `;/`:

After fixing 1, nothing happens when we have `END;/`.
Most tools are programmed to expect the `/` as the first character in a line. While it might work on a previous line in some scenarios, it could lead to unexpected behavior.
We miss a rule to check and fix this scenario.

_Solution:_ create a new rule.

--
3. `;` and `/` are distinct things:

`;` is a statement terminator
`/` is the buffer executor

The current parser code is mixing both.

_Solution:_ separate those definitions in the parser code.

--
We might need to rethink the whole approach in this PR, or just split it...
For now, I started playing with it and coded the first ideas that came to my mind.

Regarding issue #7497, I see that I made a mistake in the description by mixing the concepts of terminator and executor. I can edit later.

**Comment by keraion** [comment]
I think that makes sense. The thing I think would be a parallel concept is tsql's GO. GO isn't a statement terminator so it doesn't trigger ST12, but we have TQ03 to remove empty batches.

I guess the next challenge is the appropriate way to handle the required newline. The issue with changing the lexer is a `/` could be valid division that finds itself with a newline before it.

File: test/fixtures/dialects/oracle/declare_function_blocks.sql (hunk 1 above)
Comment (saulotoledo) [reply test/fixtures/dialects/oracle/declare_function_blocks.sql]: file removed

File: src/sqlfluff/rules/oracle/OR01.py (hunk 2 above)
Comment (saulotoledo) [reply src/sqlfluff/rules/oracle/OR01.py]: Recreated based on T-SQL one.

File: src/sqlfluff/rules/structure/ST12.py (hunk 3 above)
Comment (saulotoledo) [reply src/sqlfluff/rules/structure/ST12.py]: Not needed.

File: src/sqlfluff/dialects/dialect_oracle.py (hunk 4 above)
Comment (saulotoledo) [reply src/sqlfluff/dialects/dialect_oracle.py]: The solution was fully rewritten.

File: src/sqlfluff/rules/oracle/OR01.py
Comment (saulotoledo) [reply src/sqlfluff/rules/oracle/OR01.py:1]: The solution was fully rewritten.

**Comment by saulotoledo** [comment]
@greptileai

**Comment by saulotoledo** [comment]
@keraion This is now ready for review. Note that I've followed the T-SQL's GO as suggested.

**Comment by saulotoledo** [comment]
@greptileai
