### PR TITLE
Fix TSQL OPENROWSET for ADLS use (#5114)

### LINKED ISSUE #5114: Support Synapse Serverless OPENROWSET syntax
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have some code similar to this example code:

``` sql
SELECT *
FROM OPENROWSET(BULK 'https://<storage account>.dfs.core.windows.net/container/folder/*.parquet',
                FORMAT = 'PARQUET') AS [file]
```

When I run `sqlfluff lint`, I get:

```
Found unparsable section: "from OPENROWSET(\n        BULK 'https..."
```

### Expected Behaviour

I expect this syntax to be parsed.

### Observed Behaviour

```
❯ sqlfluff lint --dialect=tsql test.sql
== [test.sql] FAIL
L:   1 | P:   1 | AM04 | Query produces an unknown number of result columns.
                       | [ambiguous.column_count]
L:   2 | P:   1 |  PRS | Line 2, Position 1: Found unparsable section: "FROM
                       | OPENROWSET(\n    BULK 'https://examp..."
WARNING: Parsing errors found and dialect is set to 'tsql'. Have you configured your dialect correctly?
All Finished 📜 🎉!
```

### How to reproduce

```
sqlfluff lint --dialect=tsql test.sql
```
[test.zip](https://github.com/sqlfluff/sqlfluff/files/12403545/test.zip)

### Dialect

tsql

See [OPENROWSET docs](https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/develop-openrowset#syntax).

### Version

sqlfluff, version 2.3.0
Python 3.10.10

### Configuration

No configuration required to reproduce.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rayz90**
### Brief summary of the change made

Although the syntax in the docs does not reflect this, the fileformat segment is optional when using T-SQL in a SQL pool context when accessing Azure Data Lake Storage or Azure Blob Store.

It is however described in the [examples](https://learn.microsoft.com/en-us/sql/t-sql/functions/openrowset-transact-sql?view=sql-server-ver16#m-use-openrowset-to-access-several-delta-files-from-azure-data-lake-gen2).

Fixes #5114

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/tsql/openrowset.sql [hunk 1]
```diff
@@ -37,3 +37,8 @@ FROM OPENROWSET(BULK N'D:\XChange\test-csv.csv',
     FIRSTROW=2,
     FORMAT='CSV') AS cars;
 GO
+
+SELECT TOP 10 *
+from OPENROWSET(BULK 'https://pandemicdatalake.blob.core.windows.net/public/curated/covid-19/ecdc_cases/latest/ecdc_cases.parquet',
+    FORMAT = 'PARQUET') as rows
+GO
```
Comment (keraion) [inline test/fixtures/dialects/tsql/openrowset.sql:44]: nit: will you add a newline to the end of this file?

**Comment by keraion** [comment]
This is failing a black linting check. Please run black to correct this.

**Review by keraion — APPROVED** [review]
LGTM. Thanks for the contribution!
