### PR TITLE
Trino: Parse regexp_replace with lambda func

### LINKED ISSUE #5582: REGEXP_REPLACE with lambda triggers parsing errors in Trino Dialect
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I wrote some Trino SQL with a `REGEXP_REPLACE(x, y, z -> z[0])` in the query and linted it with SQLFluff. This generated a parsing error.

Upon further investigation, I found the other forms of REGEXP_REPLACE were parseable, but the one involving the lambda definition token `->` isnot.

### Expected Behaviour

I expect `REGEXP_REPLACE(x, y, z -> z[0])` to be parsable as valid syntax by SQLFluff.

### Observed Behaviour

Here's an example SQL file. I stole this example from the Trino regexp documentation [here](https://trino.io/docs/current/functions/regexp.html).

```sql
-- Capitalization method implemented via regex+lambda.
SELECT REGEXP_REPLACE('new york', '(\w)(\w*)', x -> UPPER(x[1]) || LOWER(x[2]));
```
Here's my SQLFluff command:

```bash
sqlfluff lint --dialect trino ./query.sql
```

And here's the output:

```txt
== [query.sql] FAIL
L:   1 | P:  50 |  PRS | Line 1, Position 50: Found unparsable section: '->
                       | UPPER(x[1]) || LOWER(x[2])'
WARNING: Parsing errors found and dialect is set to 'trino'. Have you configured your dialect correctly?
All Finished 📜 🎉!
```

### How to reproduce

Create a one-line SQL file called `query.sql` with the following contents:

```sql
SELECT REGEXP_REPLACE('new york', '(\w)(\w*)', x -> UPPER(x[1]) || LOWER(x[2]))
```

Then run the following command with the latest SQLFluff release:
```bash
sqlfluff lint --dialect trino ./query.sql
```

### Dialect

Trino

### Version

```bash
sqlfluff --version
sqlfluff, version 2.3.5
```

```bash
python --version
Python 3.9.16
```

### Configuration

No configuration file was used. This can be triggered with the default configuration.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rileymcdowell**
### Brief summary of the change made

This PR aims to address a particular syntax that invloves a lambda expression
inside of the REGEXP_REPLACE function.

```sql
SELECT REGEXP_REPLACE('new york', '(\w)(\w*)', x -> UPPER(x[1]) || LOWER(x[2]))
```

Fixes #5582

### Are there any other side effects of this change that we should be aware of?

I found the changes required for this from the Athena dialect implementation. Athena
and Trino share some code history, and both make use of lambda expressions for array
functions (which is not the target of this PR). I don't believe I've done enough work on
this to enable all the Trino array functions to be parseable in the Trino dialect though. 
Hopefully this is a step towards that support in the future _and_ it parses the
`REGEXP_REPLACE` with lambda parameter syntax as-is.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/trino/regexp_replace_with_lambda.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+-- The variant of REGEXP_REPLACE that accepts a function
+-- lambda expression as an argument can be tricky to parse.
+-- Signature:
+--    regexp_replace(string, pattern, function) → varchar
+-- Reference:
+--     https://trino.io/docs/422/functions/regexp.html
+
+SELECT REGEXP_REPLACE('new york', '(\w)(\w*)', x -> UPPER(x[1]) || LOWER(x[2]));
```
Comment (WittierDinosaur) [inline test/fixtures/dialects/trino/regexp_replace_with_lambda.sql:8]: nit: please add a newline here

Comment (rileymcdowell) [reply test/fixtures/dialects/trino/regexp_replace_with_lambda.sql]: I think the newline has now been added, though it's a bit hard to verify in the GitHub UI.

**Review by WittierDinosaur — APPROVED** [review]
LGTM
