### PR TITLE
Issue 845: L016 should compute line length prior to template expansion

### LINKED ISSUE #845: L016 reports "Line is too long" AFTER template expansion
## Expected Behaviour

No lint warnings.

## Observed Behaviour

Note the position (122). This line is only 53 characters long, pre-templating.
```
sqlfluff lint test.sql
== [test.sql] FAIL
L:   3 | P: 122 | L016 | Line is too long
```

## Version
SQLFluff version 0.4.1
Python version 3.7.3

## Configuration
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = bigquery
templater = jinja
rules = None
recurse = 0

[sqlfluff:templater:jinja:context]
table_at_job_start=FOR SYSTEM_TIME AS OF CAST('2021-03-02T01:22:59+00:00' AS TIMESTAMP)
bi_ecommerce_orders=mc-business-intelligence.user.ecommerce_orders
```

Query:
```
SELECT user_id
FROM
    `{{bi_ecommerce_orders}}` {{table_at_job_start}}
```

### PR DESCRIPTION
**Pull request by barrywhart**
Fixes #845 
...

### Are there any other side effects of this change that we should be aware of?
...

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

**Comment by barrywhart** [comment]
One test is failing -- need to look into that:
```
test/rules/std_fix_auto_test.py::test__std_fix_auto[bigquery-002_templating]
```

File: test/fixtures/linter/autofix/bigquery/002_templating/after.sql [hunk 1]
```diff
@@ -1,14 +1,17 @@
--- A subset of the hairy test.
-SELECT
-    COUNT(1) AS campaign_count,
-    {{corr_states}}
-    {% for action in considered_actions %}
-        , aaa(
-            bbb(ccc({{metric}}_r, {{action}}), ddd({{metric}}_r)),
```
Comment (barrywhart) [inline test/fixtures/linter/autofix/bigquery/002_templating/after.sql:7]: This test specifies `max_line_length` = 50, but this line was 67 characters long. The new result looks correct to me.

Comment (tunetheweb) [reply test/fixtures/linter/autofix/bigquery/002_templating/after.sql:7]: A reverse case of what you are trying to fix here!

Post templating this is 47-48 characters long as the template values where shorter than the template place holders.

So I agree it's correct that it now splits it with your god change as it's now looking at the placeholder lengths.

File: src/sqlfluff/rules/L016.py [hunk 2]
```diff
@@ -369,6 +369,34 @@ def _gen_line_so_far(raw_stack, initial_buff=None):
                 break  # pragma: no cover
```
Comment (tunetheweb) [inline src/sqlfluff/rules/L016.py:369]: Not related to your change, but since you're in the code here anyway, is there a test case we should add for this?

File: test/fixtures/linter/autofix/bigquery/002_templating/after.sql (hunk 1 above)
Comment (barrywhart) [reply test/fixtures/linter/autofix/bigquery/002_templating/after.sql:7]: Exactly. The previous behavior was incorrect, and often very confusing from a user perspective.

File: src/sqlfluff/rules/L016.py [hunk 3]
```diff
@@ -369,6 +369,44 @@ def _gen_line_so_far(raw_stack, initial_buff=None):
...
+        line_len = 0
+        seen_slices = set()
+        for segment in segments:
+            slice = (
+                segment.pos_marker.source_slice.start,
+                segment.pos_marker.source_slice.stop,
+            )
+            # Often, a single templated area of a source file will expand to
+            # multiple SQL tokens.Here, we use a set to avoid double counting
+            # the length of that text.
```
Comment (tunetheweb) [inline src/sqlfluff/rules/L016.py:404]: Is this due to FOR loops for example? Is it worth mentioning that to explain it?

```suggestion
            # Often, a single templated area of a source file will expand to
            # multiple SQL tokens (for example when a For loop expands multiple
            # times). We use a set to avoid double counting the length of that
            # pre-templated text.
```

Or, if not, then you at least need a space between the sentences.

File: src/sqlfluff/rules/L016.py [hunk 4]
```diff
@@ -429,7 +467,7 @@ def _eval(self, segment, raw_stack, **kwargs):
                     else:
                         break  # pragma: no cover
```
Comment (tunetheweb) [inline src/sqlfluff/rules/L016.py:468]: Same comment here about a test case if you know how to add one through your understanding of this code.

**Review by tunetheweb — APPROVED** [review]
LGTM. A few comments for you to consider.

File: src/sqlfluff/rules/L016.py (hunk 3 above)
Comment (barrywhart) [reply src/sqlfluff/rules/L016.py:404]: I'll add an example here to the comment. 👍

File: src/sqlfluff/rules/L016.py (hunk 2 above)
Comment (barrywhart) [reply src/sqlfluff/rules/L016.py:369]: I think I'll pass on adding the test cases. Some of these rules are so large and complex, you can end up fixing an issue while gaining little or no insight into other areas. 😢

Comment (tunetheweb) [reply src/sqlfluff/rules/L016.py:369]: Can't blame me for trying! 😉 Resolving.

File: src/sqlfluff/rules/L016.py (hunk 3 above)
Comment (tunetheweb) [reply src/sqlfluff/rules/L016.py]: That's much clearer now. Wasn't getting that before. Thanks.

File: src/sqlfluff/rules/L016.py (hunk 4 above)
Comment (tunetheweb) [reply src/sqlfluff/rules/L016.py:481]: Resolving as per above.
