### PR TITLE
[Vertica] fix gaps for some datatypes, complex alias support, fix group by for DDL

### LINKED ISSUE #5687: [Vertica] fix dialect mistakes
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

1. fix float with precision
2. fix according to linter
3. fix aliasing indentations
4. support aliasing for several columns in some functions
5. support array[data_type] syntax
6. allow over and within group in the same window function
7. fix interval datatype
8. fix numeric data types (no space between a type and a bracket), fix group by clause in create table partition by

### Expected Behaviour

All bugs from list above are fixed

### Observed Behaviour

All described scenarios violate some rules

### How to reproduce

I will add test cases

### Dialect

Vertica

### Version

version 3.0.0a5

### Configuration

Any configuration with vertica dialect

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by PolitePp**
### Brief summary of the change made

fixes #5687 

1. fix float with precision
3. fix aliasing indentations
4. support aliasing for several columns in some functions
5. support array[data_type] syntax
6. allow over and within group in the same window function
7. fix interval datatype
8. fix numeric data types (no space between a type and a bracket)
9. fix group by in partition by clause for create table command

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

### CODE REVIEW

File: test/fixtures/dialects/vertica/array.sql [hunk 1]
```diff
@@ -11,14 +11,15 @@ CREATE TABLE sal_emp (
...
 
-SELECT ARRAY[row(1, 2), row(1, 3)];
-
-SELECT
-    name,
-    num,
-    gpa
-FROM students
-WHERE major = ARRAY[row('Science', 'Physics')];
+-- Need to add support for complex datatypes
```
Comment (WittierDinosaur) [inline test/fixtures/dialects/vertica/array.sql:14]: This seems like a regression?

Comment (PolitePp) [reply test/fixtures/dialects/vertica/array.sql:14]: Yes, that's true, but if you try to use row datatype not inside array it will fail because it's not implemented, so it seems better to have more specific array support and later add a row datatype

Current changes in the array segment allow me to parse sections with Jinja like:
```
select
    array[
    {% for metric_event in funnel_events %}
        {% for window_size in window_sizes %}
            null,
        {% endfor %}
    {% endfor %}
    null
]::array[varchar] as agg_data
from tab;
```

Without new changes, it will violate rule RF06 Missing quoted keyword identifier varchar
